// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrjgzorlxcmqiinjqmzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impyamd6b3JseGNtcWlpbmpxbXprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzODk2MjksImV4cCI6MjA2OTk2NTYyOX0.Z3bf_rIEpe4CNqPVEx2rNxgkNk-XVANj9uAu5BBh9UA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});